# LaTeX2HTML 96.1 (Feb 5, 1996)
# Associate images original text with physical files.

$key = q/{tabular}llp317.395ptttvoid**user;SPMamp;INOUT;SPMamp;Pointertotheuser-defineddatastructure(shouldbettNULLonreturn).{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=701 HEIGHT=40 ALIGN=BOTTOM ALT="tabular501" SRC="img6.gif"  > '; 
$key = q/{tabular}lp365.945ptttERROR;SPMamp;Reverttodefault.ttUSER_AND_PP;SPMamp;Userprintedwhateverhewanted.ttDEFAULT;SPMamp;Printoutthenumberofcutsadded.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=391 HEIGHT=55 ALIGN=BOTTOM ALT="tabular1482" SRC="img73.gif"  > '; 
$key = q/{tabular}llp252.085ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintfrom;SPMamp;IN;SPMamp;Seebelowin``Notes''.ttintone_row_only;SPMamp;IN;SPMamp;ttUNPACK_CUTS_SINGLEorttUNPACK_CUTS_MULTIPLE(seenotesbelow).ttintvarnum;SPMamp;IN;SPMamp;Thenumberofvariables.ttvar_desc**vars;SPMamp;IN;SPMamp;Thevariablescurrentlyintheproblem.ttintcutnum;SPMamp;IN;SPMamp;Thenumberofcutstobedecoded.ttcut_data**cuts;SPMamp;IN;SPMamp;CutsthatneedtobeconvertedtorowsforthecurrentLP.See``Warning''below.;SPMamp;;SPMamp;ttint*new_row_num;SPMamp;OUT;SPMamp;Pointertothenumberofrowsintt**new_rows.ttwaiting_row***new_rows;SPMamp;OUT;SPMamp;Pointertothearrayofpointerstothenewrows.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=684 HEIGHT=277 ALIGN=BOTTOM ALT="tabular1430" SRC="img62.gif"  > '; 
$key = q/{tabular}llp301.645ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttchar*filename;SPMamp;IN;SPMamp;Thenameoftheparameterfile.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=507 HEIGHT=38 ALIGN=BOTTOM ALT="tabular508" SRC="img8.gif"  > '; 
$key = q/{tabular}lp365.945ptttERROR;SPMamp;Error.ThisLPsolutionisnotprocessed.ttUSER_NO_PP;SPMamp;TheuserreceivedtheLPsolution.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=418 HEIGHT=34 ALIGN=BOTTOM ALT="tabular1576" SRC="img80.gif"  > '; 
$key = q/{tabular}lp365.945ptttERROR;SPMamp;Purgeeverysinglewaitingrow.ttUSER_AND_PP;SPMamp;Theuserremovedtheunwantedwaitingrowsandcompressedtheremaininglist.ttUSER_NO_PP;SPMamp;Theusermarkedinttdeletetherowstobedeleted.ttDEFAULT;SPMamp;Describedabove.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=696 HEIGHT=99 ALIGN=BOTTOM ALT="tabular1489" SRC="img76.gif"  > '; 
$key = q/{_inline}$^copyright${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=15 HEIGHT=17 ALIGN=BOTTOM ALT="tex2html_wrap_inline2100" SRC="img3.gif"  > '; 
$key = q/{tabular}llp297.865ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttint*extravarnum;SPMamp;OUT;SPMamp;Pointertothenumberofextraactivevariablesintheroot.ttint*extravars;SPMamp;OUT;SPMamp;Pointertoanarraycontainingalistofuserindicesoftheextravariablestobeactiveintheroot.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=698 HEIGHT=77 ALIGN=BOTTOM ALT="tabular550" SRC="img19.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.TheLPprocessisaborted.ttDEFAULT;SPMamp;Upperboundsaresettoone.ttUSER_NO_PP;SPMamp;Theuserfilleduptheupperboundarray.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=423 HEIGHT=59 ALIGN=BOTTOM ALT="tabular1345" SRC="img41.gif"  > '; 
$key = q/{tabular}llp313.635ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=471 HEIGHT=12 ALIGN=BOTTOM ALT="tabular1711" SRC="img88.gif"  > '; 
$key = q/{tabular}llp313.615ptttvoid**user;SPMamp;INOUT;SPMamp;Pointertotheuser-defineddatastructure.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=519 HEIGHT=13 ALIGN=BOTTOM ALT="tabular1697" SRC="img77.gif"  > '; 
$key = q/{tabular}lp353.976ptttERROR;SPMamp;Error.Dothedefault.ttUSER_NO_PP;SPMamp;Userpackedthesolution.ttDEFAULT;SPMamp;Regulatedbytheparameterttpack_feasible_solution_default,butsettottSEND_NONZEROSunlessover-riddenbytheuser.ttSEND_NONZEROS;SPMamp;Packthenonzerovaluesandtheirindices.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=699 HEIGHT=99 ALIGN=BOTTOM ALT="tabular1361" SRC="img45.gif"  > '; 
$key = q/{tabular}lp365.945ptttERROR;SPMamp;Ignored.ttUSER_NO_PP;SPMamp;Theuserfreedalldatastructures.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=366 HEIGHT=34 ALIGN=BOTTOM ALT="tabular1584" SRC="img82.gif"  > '; 
$key = q/{_inline}$geq${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=11 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2108" SRC="img31.gif"  > '; 
$key = q/{tabular}llp322.645ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=471 HEIGHT=12 ALIGN=BOTTOM ALT="tabular516" SRC="img88.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.Thiserrorisprobablynotfatal.ttUSER_NO_PP;SPMamp;Userexecutedfunctionsuccessfully.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=402 HEIGHT=38 ALIGN=BOTTOM ALT="tabular534" SRC="img15.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Ignored.Thisisprobablynotafatalerror.ttUSER_NO_PP;SPMamp;Thesolutionhasbeenunpackedandstored.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=441 HEIGHT=38 ALIGN=BOTTOM ALT="tabular558" SRC="img21.gif"  > '; 
$key = q/{tabular}llp257.334ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintvarnum;SPMamp;IN;SPMamp;ThenumberofvariablescurrentlyintheLPrelaxation.(Thelengthofthett*varsandttxarrays.)ttvar_desc**vars;SPMamp;IN;SPMamp;ThevariablescurrentlyintheLPrelaxation.ttdouble*x;SPMamp;IN;SPMamp;Valuesoftheabovevariables.ttint*new_row_num;SPMamp;OUT;SPMamp;Thenumberofcutsgenerated.ttwaiting_row***new_rows;SPMamp;OUT;SPMamp;Thecutsandthecorrespondingrows.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=692 HEIGHT=168 ALIGN=BOTTOM ALT="tabular1469" SRC="img70.gif"  > '; 
$key = q/{tabular}lp348.725ptttERROR;SPMamp;Error.Nomessagewillbesent.ttUSER_NO_PP;SPMamp;Userpackedandsentthemessage.ttDEFAULT;SPMamp;Regulatedbythettpack_lp_solution_defaultparameter,initiallysettottSEND_NOZEROS.ttSEND_NONZEROS;SPMamp;Suserindicesandvaluesofvariablesatnonzerolevel.ttSEND_FRACTIONS;SPMamp;Suserindicesandvaluesofvariablesatfractionallevel.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=700 HEIGHT=121 ALIGN=BOTTOM ALT="tabular1440" SRC="img65.gif"  > '; 
$key = q/{_inline}$leq${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=11 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline2104" SRC="img30.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Ignored.ttUSER_NO_PP;SPMamp;Messageisprocessed.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=268 HEIGHT=38 ALIGN=BOTTOM ALT="tabular596" SRC="img27.gif"  > '; 
$key = q/{tabular}llp317.395ptttvoid**user;SPMamp;INOUT;SPMamp;Pointertotheuser-defineddatastructure.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=519 HEIGHT=13 ALIGN=BOTTOM ALT="tabular1567" SRC="img77.gif"  > '; 
$key = q/{tabular}llp301.645ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttintmsgtag;SPMamp;IN;SPMamp;ttFEASIBLE_SOLUTION_NONZEROSorttFEASIBLE_SOLUTION_USERttdoublecost;SPMamp;IN;SPMamp;Thecostofthefeasiblesolution.ttintnumvars;SPMamp;IN;SPMamp;Thenumberofvariableswhoseuserindicesandvaluesweresent(lengthofttindicesandttvalues).ttint*indices;SPMamp;IN;SPMamp;Theuserindicesofthenonzerovariables.ttdouble*values;SPMamp;IN;SPMamp;Thecorrespondingvalues.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=664 HEIGHT=146 ALIGN=BOTTOM ALT="tabular556" SRC="img20.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.scSYMPHONYabortsthisLPprocess.ttUSER_NO_PP;SPMamp;Userreceivedthedata.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=453 HEIGHT=35 ALIGN=BOTTOM ALT="tabular1322" SRC="img33.gif"  > '; 
$key = q/{tabular}lp365.945ptttERROR;SPMamp;Error.CGexits.ttUSER_NO_PP;SPMamp;Theuserreceivedthedataproperly.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=382 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1569" SRC="img78.gif"  > '; 
$key = q/{tabular}lp365.945ptttERROR;SPMamp;Error.TheLPprocessisaborted.ttUSER_AND_PP;SPMamp;Post-processingwillbeskipped,theuseraddedtheconstraintscorrespondingtothecuts.ttUSER_NO_PP;SPMamp;Usercreatedthematrixwithonlythebaseconstraints.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=696 HEIGHT=81 ALIGN=BOTTOM ALT="tabular1338" SRC="img39.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.scSYMPHONYstops.ttUSER_NO_PP;SPMamp;Theusercompletedinitializationsuccessfully.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=453 HEIGHT=38 ALIGN=BOTTOM ALT="tabular526" SRC="img13.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.scSYMPHONYstops.ttUSER_NO_PP;SPMamp;Initializationisdone.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=321 HEIGHT=34 ALIGN=BOTTOM ALT="tabular495" SRC="img5.gif"  > '; 
$key = q/{tabular}llp291.115ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintvarnum;SPMamp;IN;SPMamp;Numberofvariablesintherelaxation(baseandextra).ttvar_desc**vars;SPMamp;IN;SPMamp;Anarrayoflengthttncontainingtheuserindicesoftheactivevariables(baseandextra).ttintrownum;SPMamp;IN;SPMamp;Numberofconstraintsintherelaxation(baseandextra).ttintcutnum;SPMamp;IN;SPMamp;Numberofextraconstraints.ttcut_data**cuts;SPMamp;IN;SPMamp;Packeddescriptionofextraconstraints.;SPMamp;;SPMamp;ttint*nz;SPMamp;OUT;SPMamp;PointertothenumberofnonzerosintheLP.ttint**matbeg;SPMamp;INOUT;SPMamp;PointerstothearraysthatdescribetheLPproblem(seedescriptionabove.ttint**matind;SPMamp;INOUT;SPMamp;ttdouble**matval;SPMamp;INOUT;SPMamp;ttdouble**obj;SPMamp;INOUT;SPMamp;ttdouble**rhs;SPMamp;INOUT;SPMamp;ttchar**sense;SPMamp;INOUT;SPMamp;ttdouble**rngval;SPMamp;INOUT;SPMamp;;SPMamp;;SPMamp;ttint*maxn;SPMamp;INOUT;SPMamp;Themaximumnumberofvariables.ttint*maxm;SPMamp;INOUT;SPMamp;Themaximumnumberofconstraints.ttint*maxnz;SPMamp;INOUT;SPMamp;Themaximumnumberofnonzeros.;SPMamp;;SPMamp;ttint*allocn;SPMamp;INOUT;SPMamp;Thelengthofthett*matbegandtt*objarrays(shouldbett*maxm+*maxn+1).ttint*allocm;SPMamp;INOUT;SPMamp;Thelengthofthett*rhs,tt*senseandtt*rngvalarrays.ttint*allocnz;SPMamp;INOUT;SPMamp;Thelengthofthett*matvalandtt*matindarrays(shouldbett*maxnz+*maxm.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=697 HEIGHT=596 ALIGN=BOTTOM ALT="tabular1336" SRC="img38.gif"  > '; 
$key = q/{tabular}llp303.114ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttcut_data*cut1;SPMamp;IN;SPMamp;Thefirstcut.ttcut_data*cut2;SPMamp;IN;SPMamp;Thesecondcut.ttint*same_cuts;SPMamp;OUT;SPMamp;Possiblevalues:ttSAME,ttFIRST_CUT_BETTER,ttSECOND_CUT_BETTERandttDIFFERENT(i.e.,notcomparable).{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=685 HEIGHT=125 ALIGN=BOTTOM ALT="tabular1423" SRC="img60.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.TheLPprocessisaborted.ttUSER_NO_PP;SPMamp;Userfilledouttt*real_nextindandgenerateditscolumnifneeded.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=612 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1461" SRC="img69.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.ttDEFAULTisused.ttUSER_NO_PP;SPMamp;Theuserfilledouttt*action(andpossiblytt*cand_numandtt*candidates).ttDEFAULT;SPMamp;actionissettothevalueoftheparameterttshall_we_branch_default,whichisinitiallyttUSER__BRANCH_IF_MUSTunlessover-riddenbytheuser.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=696 HEIGHT=81 ALIGN=BOTTOM ALT="tabular1378" SRC="img50.gif"  > '; 
$key = q/{tabular}lp365.945ptttERROR;SPMamp;CutsarenotcheckedforthisLPsolution.ttUSER_NO_PP;SPMamp;Theuserispreparedtocheckcuts.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=425 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1721" SRC="img91.gif"  > '; 
$key = q/{tabular}llp301.645ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttdoublelpetol;SPMamp;IN;SPMamp;The_inline$epsilon$_inlinetoleranceoftheLPsolver.ttintvarnum;SPMamp;IN;SPMamp;Thelengthofthettindicesandttvaluesarrays.ttint*indices;SPMamp;IN;SPMamp;Userindicesofvariablesatnonzerolevelinthecurrentsolution.ttdouble*values;SPMamp;IN;SPMamp;Valuesofthevariableslistedinttindices.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=664 HEIGHT=121 ALIGN=BOTTOM ALT="tabular1359" SRC="img44.gif"  > '; 
$key = q/{tabular}llp317.395ptttvoid**user;SPMamp;OUT;SPMamp;Pointertotheuser-defineddatastructure.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=500 HEIGHT=13 ALIGN=BOTTOM ALT="tabular493" SRC="img4.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.Thecutsarediscarded.ttUSER_NO_PP;SPMamp;Userunpackedthecuts.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=337 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1432" SRC="img63.gif"  > '; 
$key = q/{tabular}llp292.615ptttvoid*user;SPMamp;INOUT;SPMamp;Theuserdefinedpartofp.ttdoublelpetol;SPMamp;IN;SPMamp;The_inline$epsilon$_inlinetoleranceintheLPprocess.ttintvarnum;SPMamp;IN;SPMamp;Sameasthepreviousfunction.ttint*indices;SPMamp;IN;SPMamp;Sameasthepreviousfunction.ttdouble*values;SPMamp;IN;SPMamp;Sameasthepreviousfunction.ttcut_data*cut;SPMamp;IN;SPMamp;Pointertothecuttobetested.ttint*is_violated;SPMamp;OUT;SPMamp;TRUEFALSEbasedonwhetherthecutisviolatedornot.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=693 HEIGHT=147 ALIGN=BOTTOM ALT="tabular1726" SRC="img92.gif"  > '; 
$key = q/{tabular}llp317.395pt;SPMamp;;SPMamp;ttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.ttintvarnum;SPMamp;IN;SPMamp;Lengthofttvars.ttint*vars;SPMamp;IN;SPMamp;Arraycontainingtheuserindicesofthevariables.ttdouble*ub;SPMamp;OUT;SPMamp;Arrayofupperbounds(tobefilledoutbytheuser).{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=570 HEIGHT=82 ALIGN=BOTTOM ALT="tabular1343" SRC="img40.gif"  > '; 
$key = q/{tabular}llp297.864ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttint*desc_size;SPMamp;OUT;SPMamp;Thesizeoftheadditionalinformation,thelengthoftt*descinbytes.ttchar**desc;SPMamp;OUT;SPMamp;Pointertotheadditionalinformation(spacemustbeallocatedbytheuser).{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=675 HEIGHT=125 ALIGN=BOTTOM ALT="tabular1416" SRC="img58.gif"  > '; 
$key = q/{tabular}llp297.864ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintvarnum;SPMamp;IN;SPMamp;ThenumberofvariablescurrentlyintheLPrelaxation.(Thelengthofthett*varsandttxarrays.)ttvar_desc**vars;SPMamp;IN;SPMamp;ThevariablescurrentlyintheLPrelaxation.ttdouble*x;SPMamp;IN;SPMamp;Valuesoftheabovevariables.ttchar*status;SPMamp;INOUT;SPMamp;StatiofvariablescurrentlyintheLPrelaxation.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=704 HEIGHT=146 ALIGN=BOTTOM ALT="tabular1446" SRC="img66.gif"  > '; 
$key = q/{_inline}$ttrhs+ttrange${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=92 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2102" SRC="img29.gif"  > '; 
$key = q/{_inline}$1^st${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=21 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline2128" SRC="img37.gif"  > '; 
$key = q/{tabular}llp297.865ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttbranch_obj*can;SPMamp;IN;SPMamp;Thebranchingcandidate.ttcut_data*cut;SPMamp;IN;SPMamp;Thedescriptionofthecutifthebranchingobjectisacut.ttchar*action;SPMamp;IN;SPMamp;Arrayofactionsforthechildren.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=637 HEIGHT=103 ALIGN=BOTTOM ALT="tabular1408" SRC="img56.gif"  > '; 
$key = q/{tabular}llp297.864ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintub;SPMamp;IN;SPMamp;Thecurrentbestupperbound.ttdoubleetol;SPMamp;IN;SPMamp;Epsilontolerance.ttbranch_obj*can;SPMamp;IN;SPMamp;Thebranchingcandidate.;SPMamp;;SPMamp;ttchar*action;SPMamp;OUT;SPMamp;Arrayofactionsforthechildren.Thearrayisalreadyallocatedtolengthttcan-;SPMgt;number.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=686 HEIGHT=167 ALIGN=BOTTOM ALT="tabular1399" SRC="img54.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.scSYMPHONYstops.ttUSER_NO_PP;SPMamp;Allrequireddatafilledout,butnopost-processingdone.ttUSER_AND_PP;SPMamp;Allrequiredpost-processingdone.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=548 HEIGHT=59 ALIGN=BOTTOM ALT="tabular547" SRC="img18.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.ttDEFAULTisused.ttUSER_NO_PP;SPMamp;Userfilledouttt*desc_sizeandtt*desc.ttDEFAULT;SPMamp;Nodescriptionisapped.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=398 HEIGHT=59 ALIGN=BOTTOM ALT="tabular1418" SRC="img59.gif"  > '; 
$key = q/{tabular}llp260.256ptttintvarnum;SPMamp;IN;SPMamp;Thenumberofvariablesinthecurrentlprelaxation(thelengthofthefollowingthreearrays).ttvar_desc**vars;SPMamp;IN;SPMamp;Descriptionofthevariablesintherelaxation.ttdouble*x;SPMamp;IN;SPMamp;Thecorrespondingsolutionvalues(intheoptimalsolutiontotherelaxation).ttchar*status;SPMamp;IN;SPMamp;Thestatiofthevariables.Therearefivepossiblestatusvalues:ttNOT_-FIXED,ttTEMP_-FIXED_-TO_-UB,ttPERM_-FIXED_-TO_-UB,ttTEMP_-FIXED_-TO_-LBandttPERM_-FIXED_-TO_-LB.;SPMamp;;SPMamp;ttint*cand_num;SPMamp;OUT;SPMamp;Pointertothenumberofcandidatesreturned(thelengthoftt*candidates).ttcandidate***candidates;SPMamp;OUT;SPMamp;Pointertothearrayofcandidatesgenerated(seedescriptionbelow).ttint*action;SPMamp;OUT;SPMamp;Whattodo.Mustbeoneofthefourabovedescribedvalues.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=701 HEIGHT=315 ALIGN=BOTTOM ALT="tabular1376" SRC="img49.gif"  > '; 
$key = q/{tabular}lp295.386ptttERROR;SPMamp;Error.ttDEFAULTisused.ttUSER_NO_PP;SPMamp;Userdidthecomparison,filledouttt*same_cuts.ttDEFAULT;SPMamp;Comparebytebybyte(seeabove).{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=470 HEIGHT=60 ALIGN=BOTTOM ALT="tabular1425" SRC="img61.gif"  > '; 
$key = q/{tabular}lp365.945ptttERROR;SPMamp;CutsarenotcheckedforthisLPsolution.ttUSER_NO_PP;SPMamp;Theuserfunctionexitedproperly.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=425 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1713" SRC="img89.gif"  > '; 
$key = q/{tabular}llp322.645ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttvoid**user_cg;SPMamp;OUT;SPMamp;Pointertotheuser-defineddatastructureforthecutgeneratorprocess.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=715 HEIGHT=55 ALIGN=BOTTOM ALT="tabular571" SRC="img24.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.scSYMPHONYstops.ttUSER_NO_PP;SPMamp;Userparameterswerereadsuccessfully.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=405 HEIGHT=38 ALIGN=BOTTOM ALT="tabular510" SRC="img9.gif"  > '; 
$key = q/{tabular}llp317.395ptttvoid**user;SPMamp;OUT;SPMamp;Pointertotheuser-definedLPdatastructure.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=528 HEIGHT=13 ALIGN=BOTTOM ALT="tabular1320" SRC="img32.gif"  > '; 
$key = q/{tabular}lp350.196ptttERROR;SPMamp;Error.scSYMPHONYignoreserrormessage.ttUSER_NO_PP;SPMamp;Userdisplayedwhatevershewantedto.ttDEFAULT;SPMamp;Regulatedbytheparameterttdisplay_solution_default.ttDISP_NOTHING;SPMamp;Displaynothing.ttDISP_NZ_INT;SPMamp;Displayuserindices(asintegers)andvaluesofnonzerovariables.ttDISP_NZ_HEXA;SPMamp;Displayuserindices(ashexadecimals)andvaluesofnonzerovariables.ttDISP_FRAC_INT;SPMamp;Displayuserindices(asintegers)andvaluesofvariablesnotattheirlowerorupperbounds.ttDISP_FRAC_HEXA;SPMamp;Displayuserindices(ashexadecimals)andvaluesofvariablesnotattheirlowerandupperbounds.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=699 HEIGHT=211 ALIGN=BOTTOM ALT="tabular1368" SRC="img47.gif"  > '; 
$key = q/{tabular}lp256.327ptttERROR;SPMamp;Error.ttDEFAULTisused.ttUSER_NO_PP;SPMamp;Usergeneratedbranchingcandidates.ttDEFAULT;SPMamp;Regulatedbythettselect_candidates_defaultparameter(oneofthefollowingthreeoptions).ttUSER__CLOSE_TO_HALF;SPMamp;Choosevariableswithvaluesclosesttohalf.ttUSER__CLOSE_TO_HALF_AND_EXPENSIVE;SPMamp;Choosevariableswithvaluesclosetohalfandwithhighobjectivefunctioncoefficients.ttUSER__CLOSE_TO_ONE_AND_CHEAP;SPMamp;Choosevariableswithvaluesclosetooneandwithlowobjectivefunctioncoefficients.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=714 HEIGHT=189 ALIGN=BOTTOM ALT="tabular1386" SRC="img51.gif"  > '; 
$key = q/{tabular}llp297.864ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintvarnum;SPMamp;IN;SPMamp;ThenumberofvariablescurrentlyintheLPrelaxation.(Thelengthofthett*varsandttxarrays.)ttvar_desc**vars;SPMamp;IN;SPMamp;ThevariablescurrentlyintheLPrelaxation.ttdouble*x;SPMamp;IN;SPMamp;Valuesoftheabovevariables.ttintwhere;SPMamp;IN;SPMamp;Wherethesolutionistobesent---ttLP_SOL_TO_CGorttLP_SOL_TO_CP.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=665 HEIGHT=163 ALIGN=BOTTOM ALT="tabular1438" SRC="img64.gif"  > '; 
$key = q/{tabular}lp338.226ptttERROR;SPMamp;Error.Solutionisconsideredtobenotfeasible.ttUSER_NO_PP;SPMamp;UsercheckedIPfeasibility.ttDEFAULT;SPMamp;Regulatedbytheparameterttis_feasible_default,butsettottTEST_INTEGRALITYunlessover-riddenbytheuser.ttTEST_INTEGRALITY;SPMamp;Testintegralityofthegivensolution.ttTEST_ZERO_ONE;SPMamp;Testswhetherthesolutionisbinary.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=701 HEIGHT=124 ALIGN=BOTTOM ALT="tabular1354" SRC="img43.gif"  > '; 
$key = q/{tabular}llp301.645ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintwhich_sol;SPMamp;IN;SPMamp;Thetypeofsolutionpassedontothedisplayingfunction.PossiblevaluesarettDISP_FEAS_SOLUTION,ttDISP_RELAXED_SOLUTIONandttDISP_FINAL_RELAXED_SOLUTION.ttintvarnum;SPMamp;IN;SPMamp;Thenumberofvariablesinthecurrentsolutionatnonzerolevel(thelengthofthettindicesandttvaluesarrays).ttint*indices;SPMamp;IN;SPMamp;Userindicesofvariablesatnonzerolevelinthecurrentsolution.ttdouble*values;SPMamp;IN;SPMamp;Valuesofthenonzerovariables.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=665 HEIGHT=186 ALIGN=BOTTOM ALT="tabular1366" SRC="img46.gif"  > '; 
$key = q/{tabular}llp317.395ptttvoid**user;SPMamp;INOUT;SPMamp;Pointertotheuser-defineddatastructure(shouldbettNULLonexitfromthisfunction).{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=701 HEIGHT=40 ALIGN=BOTTOM ALT="tabular1582" SRC="img81.gif"  > '; 
$key = q/{tabular}llp313.615ptttvoid**user;SPMamp;INOUT;SPMamp;Pointertotheuser-defineddatastructure(shouldbettNULLonexit).{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=695 HEIGHT=18 ALIGN=BOTTOM ALT="tabular1704" SRC="img87.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.scSYMPHONYstops.ttUSER_NO_PP;SPMamp;Therequireddataarefilledin,butnopost-processingdone.ttUSER_AND_PP;SPMamp;Allrequiredpost-processingdone.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=574 HEIGHT=59 ALIGN=BOTTOM ALT="tabular541" SRC="img17.gif"  > '; 
$key = q/{_inline}$^ttth${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=13 HEIGHT=8 ALIGN=BOTTOM ALT="tex2html_wrap_inline2150" SRC="img74.gif"  > '; 
$key = q/{tabular}llp322.645ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttvoid**user_cp;SPMamp;OUT;SPMamp;Pointertotheuser-defineddatastructureforthecutpoolprocess.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=711 HEIGHT=38 ALIGN=BOTTOM ALT="tabular580" SRC="img25.gif"  > '; 
$key = q/{tabular}lp327.725ptttERROR;SPMamp;Error.ttDEFAULTisused.ttUSER_NO_PP;SPMamp;Userfilledouttt*which_is_better.ttDEFAULT;SPMamp;Regulatedbythettcompare_candidates_defaultparameter,initiallysettottLOWEST_LOW_OBJunlessover-riddenbytheuser.ttBIGGEST_DIFFERENCE;SPMamp;Preferthecandidatewiththebiggestdifferencebetweenhighestandlowestobjectivefunctionvalues.ttLOWEST_LOW;SPMamp;Preferthecandidatewiththelowestminimumobjectivefunctionvalue.Theminimumistakenovertheobjectivefunctionvaluesofallthechildren.ttHIGHEST_LOW;SPMamp;Preferthecandidatewiththehighestminimumobjectivefunctionvalue.ttLOWEST_HIGH;SPMamp;Preferthecandidatewiththelowestmaximumobjectivefunctionvalue.ttHIGHEST_HIGH;SPMamp;Preferthecandidatewiththehighestmaximumobjectivefunctionvalue.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=702 HEIGHT=315 ALIGN=BOTTOM ALT="tabular1393" SRC="img53.gif"  > '; 
$key = q/{tabular}llp317.395ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=471 HEIGHT=12 ALIGN=BOTTOM ALT="tabular1574" SRC="img88.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.IgnoredbyscSYMPHONY.ttUSER_NO_PP;SPMamp;Theuserprintedoutwhatevershewantedto.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=455 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1410" SRC="img57.gif"  > '; 
$key = q/{tabular}lp365.945ptttERROR;SPMamp;Ignored.ttUSER_NO_PP;SPMamp;Theuserfunctionexitedproperly.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=365 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1591" SRC="img84.gif"  > '; 
$key = q/{tabular}llp306.895ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttintiter_num;SPMamp;IN;SPMamp;TheiterationnumberofthecurrentLPsolution.ttintlevel;SPMamp;IN;SPMamp;ThelevelinthetreeonwhichthecurrentLPsolutionwasgenerated.ttindex;SPMamp;IN;SPMamp;TheindexofthenodeinwhichLPsolutionwasgenerated.ttobjval;SPMamp;IN;SPMamp;TheobjectivefunctionvalueofthecurrentLPsolution.ttintvarnum;SPMamp;IN;SPMamp;ThenumberofnonzerosinthecurrentLPsolution.ttindices;SPMamp;IN;SPMamp;ThecolumnindicesofthenonzerovariablesinthecurrentLPsolution.ttvalues;SPMamp;IN;SPMamp;Thevaluesofthenonzerovariableslistedinttindices.ttdoubleub;SPMamp;IN;SPMamp;Thecurrentglobalupperbound.ttdoublelpetol;SPMamp;IN;SPMamp;ThecurrenterrortoleranceintheLP.ttint*cutnum;SPMamp;OUT;SPMamp;PointertothenumberofcutsgeneratedandsenttotheLP.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=683 HEIGHT=276 ALIGN=BOTTOM ALT="tabular1589" SRC="img83.gif"  > '; 
$key = q/{_inline}$0^th${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=23 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline2126" SRC="img36.gif"  > '; 
$key = q/{tabular}llp322.645ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttint*ub;SPMamp;OUT;SPMamp;Pointertotheglobalupperbound.Initially,theupperboundissettoeithertt-MAXDOUBLEortheboundreadinfromtheparameterfile,andshouldbechangedbytheuseronlyifabettervalidupperboundisfound.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=681 HEIGHT=99 ALIGN=BOTTOM ALT="tabular532" SRC="img14.gif"  > '; 
$key = q/{tabular}lp365.945ptttERROR;SPMamp;Error.Interpretedasifnocutsweregenerated.ttUSER_NO_PP;SPMamp;CutsweregeneratedbutscSYMPHONYmustcomparethemtothoseinthelocalpool.ttUSER_AND_PP;SPMamp;CutsweregeneratedandscSYMPHONYshouldnotcomparethemtothoseinthelocalpool.ttDEFAULT;SPMamp;Nocutsaregenerated.(Atleastfornow.WemightaddGomorycutsfordefaultlater.){tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=697 HEIGHT=147 ALIGN=BOTTOM ALT="tabular1471" SRC="img71.gif"  > '; 
$key = q/{tabular}llp282.115ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintrownum;SPMamp;IN;SPMamp;Thenumberofwaitingrows.ttwaiting_row**rows;SPMamp;IN;SPMamp;Thearrayofwaitingrows.ttchar*delete;SPMamp;OUT;SPMamp;Anarrayofindicators(eachofthemisonettchar)showingwhichwaitingrowsaretobedeleted.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=688 HEIGHT=124 ALIGN=BOTTOM ALT="tabular1487" SRC="img75.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Ignored.ttUSER_NO_PP;SPMamp;Displayingisdone.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=249 HEIGHT=38 ALIGN=BOTTOM ALT="tabular588" SRC="img26.gif"  > '; 
$key = q/{tabular}llp301.645ptttvoid*user;SPMamp;INOUT;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttdoublelpetol;SPMamp;IN;SPMamp;The_inline$epsilon$_inlinetoleranceoftheLPsolver.ttintvarnum;SPMamp;IN;SPMamp;Thelengthofthettindicesandttvaluesarrays.ttint*indices;SPMamp;IN;SPMamp;Userindicesofvariablesatnonzerolevelinthecurrentsolution.ttdouble*values;SPMamp;IN;SPMamp;Valuesofthevariableslistedinttindices.;SPMamp;;SPMamp;ttint*feasible;SPMamp;OUT;SPMamp;Feasibilitystatusofthesolution(ttNOT_FEASIBLE,orttFEASIBLE).{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=704 HEIGHT=168 ALIGN=BOTTOM ALT="tabular1352" SRC="img42.gif"  > '; 
$key = q/{tabular}llp322.645ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttintdg_id;SPMamp;IN;SPMamp;Theprocessidofthegraphdrawingprocess.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=490 HEIGHT=39 ALIGN=BOTTOM ALT="tabular524" SRC="img12.gif"  > '; 
$key = q/{tabular}llp301.645ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttintvarnum;SPMamp;IN;SPMamp;Thenumberofnonzerofractionalvariablesdescribedinttindicesandttvalues.ttint*indices;SPMamp;IN;SPMamp;Theuserindicesofthenonzerofractionalvariables.ttdouble*values;SPMamp;IN;SPMamp;Thenonzerofractionalvalues.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=664 HEIGHT=104 ALIGN=BOTTOM ALT="tabular1719" SRC="img90.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Ignored.Thisisprobablynotafatalerror.ttUSER_NO_PP;SPMamp;Everythingwasfreedsuccessfully.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=434 HEIGHT=38 ALIGN=BOTTOM ALT="tabular503" SRC="img7.gif"  > '; 
$key = q/{tabular}lp365.945ptttERROR;SPMamp;CutisnotsenttotheLP,regardlessofthevalueoftt*is_violated.ttUSER_NO_PP;SPMamp;Theuserfunctionexitedproperly.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=616 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1728" SRC="img93.gif"  > '; 
$key = q/{tabular}llp287.365ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintgenerate_what;SPMamp;IN;SPMamp;ttGENERATE_NEXTINDorttGENERATE_REAL_NEXTIND(seedescriptionabove).ttintcutnum;SPMamp;IN;SPMamp;ThenumberofaddedrowsintheLPformulation(i.e.,thetotalnumberofrowslessthenumberofbaseconstraints).Thisisthelengthofthett**cutsarray.ttcut_data**cuts;SPMamp;IN;SPMamp;DescriptionofthecutscorrespondingtotheaddedrowsofthecurrentLPformulation.Theuserissupposedtoknowaboutthecutscorrespondingtothebaseconstraints.ttintprevind;SPMamp;IN;SPMamp;Thelastvariableprocessed(_inline$-1$_inlineiftherewasnone)byscSYMPHONY.ttintnextind;SPMamp;IN;SPMamp;Thenextvariable(_inline$-1$_inlineiftherearenone)knowntoscSYMPHONY.;SPMamp;;SPMamp;ttint*real_nextind;SPMamp;OUT;SPMamp;Pointertotheuserindexofthenextvariable(_inline$-1$_inlineifthereisnone).ttdouble*colval;SPMamp;OUT;SPMamp;Valuesofthenonzeroentriesinthecolumnofthenextvariable.(Sufficientspaceisalreadyallocatedforthisarray.)ttint*colind;SPMamp;OUT;SPMamp;Rowindicesofthenonzeroentriesinthecolumn.(Sufficientspaceisalreadyallocatedforthisarray.)ttint*collen;SPMamp;OUT;SPMamp;Thelengthofthettcolvalandttcolindarrays.ttdouble*obj;SPMamp;OUT;SPMamp;Objectivecoefficientcorrespondingtothenextvariable.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=688 HEIGHT=492 ALIGN=BOTTOM ALT="tabular1457" SRC="img68.gif"  > '; 
$key = q/{tabular}lp304.416ptttERROR;SPMamp;Error.ttDEFAULTisused.ttUSER_NO_PP;SPMamp;Userfilledouttt*action.ttUSER_AND_PP;SPMamp;Userfilledouttt*actionanddidanequivalentofthepost-processing.ttDEFAULT;SPMamp;Regulatedbythettselect_child_defaultparameter,whichisinitiallysettottPREFER_LOWER_OBJ_VALUE,unlessover-riddenbytheuser.ttPREFER_HIGHER_OBJ_VALUE;SPMamp;Choosechildwiththehighestobjectivevalue.ttPREFER_LOWER_OBJ_VALUE;SPMamp;Choosechildwiththelowestobjectivevalue.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=707 HEIGHT=189 ALIGN=BOTTOM ALT="tabular1401" SRC="img55.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.scSYMPHONYignoreserrormessage.ttUSER_NO_PP;SPMamp;Userfreedeverythingintheuserspace.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=445 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1330" SRC="img35.gif"  > '; 
$key = q/{tabular}llp322.645ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttintmsgtag;SPMamp;IN;SPMamp;Themessagetagofthemessage.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=471 HEIGHT=39 ALIGN=BOTTOM ALT="tabular598" SRC="img28.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.scSYMPHONYstops.ttUSER_NO_PP;SPMamp;Packingisdone.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=321 HEIGHT=38 ALIGN=BOTTOM ALT="tabular565" SRC="img23.gif"  > '; 
$key = q/{tabular}llp322.645ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttvoid**user_lp;SPMamp;OUT;SPMamp;Pointertotheuser-defineddatastructurefortheLPprocess.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=670 HEIGHT=38 ALIGN=BOTTOM ALT="tabular563" SRC="img22.gif"  > '; 
$key = q/{tabular}llp317.395ptttvoid**user;SPMamp;INOUT;SPMamp;Pointertotheuser-definedLPdatastructure.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=548 HEIGHT=13 ALIGN=BOTTOM ALT="tabular1328" SRC="img34.gif"  > '; 
$key = q/{tabular}llp297.865ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttint*varnum;SPMamp;OUT;SPMamp;Pointertothenumberofbasevariables.ttint**userind;SPMamp;OUT;SPMamp;Pointertoanarraycontainingtheuserindicesofthebasevariables.ttint**lb;SPMamp;OUT;SPMamp;Pointertoanarraycontainingthelowerboundsforthebasevariables.ttint**ub;SPMamp;OUT;SPMamp;Pointertoanarraycontainingtheupperboundsforthebasevariables.ttint*cutnum;SPMamp;OUT;SPMamp;Thenumberofbaseconstraints.ttint*colgen_strat;SPMamp;INOUT;SPMamp;Thedefaultstrategyoronethathasbeenreadinfromtheparameterfileispassedin,buttheuserisfreetochangeit.Seettcolgen_stratinthedescriptionofparametersfordetailsonhowtosetit.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=722 HEIGHT=272 ALIGN=BOTTOM ALT="tabular539" SRC="img16.gif"  > '; 
$key = q/{tabular}llp282.115ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintrownum;SPMamp;IN;SPMamp;Thenumberofcutsadded.ttwaiting_row**rows;SPMamp;IN;SPMamp;Arrayofwaitingrowscontainingthecutsadded.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=593 HEIGHT=82 ALIGN=BOTTOM ALT="tabular1480" SRC="img72.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.scSYMPHONYstops.ttUSER_NO_PP;SPMamp;UserIOwascompletedsuccessfully.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=387 HEIGHT=39 ALIGN=BOTTOM ALT="tabular518" SRC="img11.gif"  > '; 
$key = q/{tabular}lp322.779ptttERROR;SPMamp;Errorintheuserfunction.Printinganerrormessageistheuser'sresponsibility.Depingontheworktheuserfunctionwassupposedtodo,theerrormightbeignored(andsomedefaultoptionused),ortheprocessaborts.ttUSER_AND_PP;SPMamp;Theuserimplementedboththeuserfunctionandpost-processing(post-processingbyscSYMPHONYwillbeskipped).ttUSER_NO_PP;SPMamp;Theuserimplementedtheuserfunctiononly.ttDEFAULT;SPMamp;Thedefaultoptionisgoingtobeused(thedefaultisoneofthebuilt-inoptions,scSYMPHONYdecideswhichonetousebasedoninitialparametersettingsandtheexecutionofthealgorithm).ttbuilt_in_option1;SPMamp;ttbuilt_in_option2...;SPMamp;Thespecifiedbuilt-inoptionwillbeused.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=704 HEIGHT=254 ALIGN=BOTTOM ALT="tabular168" SRC="img2.gif"  > '; 
$key = q/{tabular}lp365.945ptttERROR;SPMamp;Error.CutPoolexits.ttUSER_NO_PP;SPMamp;Theuserreceiveddatasuccessfully.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=374 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1699" SRC="img86.gif"  > '; 
$key = q/{tabular}llp273.085ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttbranch_obj*can1;SPMamp;IN;SPMamp;Oneofthecandidatestobecompared.ttbranch_obj*can2;SPMamp;IN;SPMamp;Theothercandidatetobecompared.ttint*which_is_better;SPMamp;OUT;SPMamp;Theuser'schoice.Seethedescriptionabove.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=607 HEIGHT=103 ALIGN=BOTTOM ALT="tabular1391" SRC="img52.gif"  > '; 
$key = q/{tabular}lp371.195ptttERROR;SPMamp;Error.IgnoredbyscSYMPHONY.ttUSER_NO_PP;SPMamp;Userchangedthestatiofthevariablesshewanted.{tabular}/;
$cached_env_img{$key} = ' <IMG WIDTH=494 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1448" SRC="img67.gif"  > '; 

1;

