# LaTeX2HTML 96.1 (Feb 5, 1996)
# Associate images original text with physical files.

$key = q/{tabular}lp300ptttERROR;SPMamp;Error.CutPoolexits.ttUSER_NO_PP;SPMamp;Theuserreceiveddatasuccessfully.{tabular}/;
${$key} = ' <IMG WIDTH=374 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1926" SRC="img89.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.Ignored.ttUSER_NO_PP;SPMamp;Theusersuccessfullyinterpretedthetext.{tabular}/;
${$key} = ' <IMG WIDTH=425 HEIGHT=38 ALIGN=BOTTOM ALT="tabular2036" SRC="img102.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.Messageignored.ttUSER_NO_PP;SPMamp;Theuserprocessedthemessage.{tabular}/;
${$key} = ' <IMG WIDTH=351 HEIGHT=38 ALIGN=BOTTOM ALT="tabular2015" SRC="img97.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.scSYMPHONYabortsthisLPprocess.ttUSER_NO_PP;SPMamp;Userreceivedthedata.{tabular}/;
${$key} = ' <IMG WIDTH=452 HEIGHT=36 ALIGN=BOTTOM ALT="tabular1524" SRC="img35.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.scSYMPHONYstops.ttUSER_NO_PP;SPMamp;Userparameterswerereadsuccessfully.{tabular}/;
${$key} = ' <IMG WIDTH=405 HEIGHT=39 ALIGN=BOTTOM ALT="tabular681" SRC="img9.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Reverttodefault.ttUSER_AND_PP;SPMamp;Userprintedwhateverhewanted.ttDEFAULT;SPMamp;Printoutthenumberofcutsadded.{tabular}/;
${$key} = ' <IMG WIDTH=390 HEIGHT=55 ALIGN=BOTTOM ALT="tabular1683" SRC="img74.gif"  > '; 
$key = q/{tabular}llp280ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.{tabular}/;
${$key} = ' <IMG WIDTH=471 HEIGHT=12 ALIGN=BOTTOM ALT="tabular687" SRC="img80.gif"  > '; 
$key = q/{_inline}$^copyright${_inline}/;
${$key} = ' <IMG WIDTH=16 HEIGHT=17 ALIGN=BOTTOM ALT="tex2html_wrap_inline2620" SRC="img3.gif"  > '; 
$key = q/{tabular}lp260ptttERROR;SPMamp;Solutiontracingisnotenabled.ttUSER_NO_PP;SPMamp;Tracingofthegivensolutionisenabled.{tabular}/;
${$key} = ' <IMG WIDTH=410 HEIGHT=38 ALIGN=BOTTOM ALT="tabular770" SRC="img28.gif"  > '; 
$key = q/{tabular}llp275ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttvoid**user_lp;SPMamp;OUT;SPMamp;Pointertotheuser-defineddatastructurefortheLPprocess.{tabular}/;
${$key} = ' <IMG WIDTH=639 HEIGHT=55 ALIGN=BOTTOM ALT="tabular735" SRC="img22.gif"  > '; 
$key = q/{_inline}$geq${_inline}/;
${$key} = ' <IMG WIDTH=11 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2628" SRC="img33.gif"  > '; 
$key = q/{tabular}llp275ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttint*desc_size;SPMamp;OUT;SPMamp;Thesizeoftheadditionalinformation,thelengthoftt*descinbytes.ttchar**desc;SPMamp;OUT;SPMamp;Pointertotheadditionalinformation(spacemustbeallocatedbytheuser).{tabular}/;
${$key} = ' <IMG WIDTH=639 HEIGHT=124 ALIGN=BOTTOM ALT="tabular1616" SRC="img59.gif"  > '; 
$key = q/{tabular}llp245ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttbranch_obj*can1;SPMamp;IN;SPMamp;Oneofthecandidatestobecompared.ttbranch_obj*can2;SPMamp;IN;SPMamp;Theothercandidatetobecompared.ttint*which_is_better;SPMamp;OUT;SPMamp;Theuser'schoice.Seethedescriptionabove.{tabular}/;
${$key} = ' <IMG WIDTH=606 HEIGHT=103 ALIGN=BOTTOM ALT="tabular1591" SRC="img53.gif"  > '; 
$key = q/{tabular}llp250pt;SPMamp;;SPMamp;ttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.ttintvarnum;SPMamp;IN;SPMamp;Lengthofttvars.ttint*vars;SPMamp;IN;SPMamp;Arraycontainingtheuserindicesofthevariables.ttdouble*ub;SPMamp;OUT;SPMamp;Arrayofupperbounds(tobefilledoutbytheuser).{tabular}/;
${$key} = ' <IMG WIDTH=566 HEIGHT=81 ALIGN=BOTTOM ALT="tabular1545" SRC="img42.gif"  > '; 
$key = q/{tabular}llp260ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintgenerate_what;SPMamp;IN;SPMamp;ttGENERATE_NEXTINDorttGENERATE_REAL_NEXTIND(seedescriptionabove).ttintcutnum;SPMamp;IN;SPMamp;ThenumberofaddedrowsintheLPformulation(i.e.,thetotalnumberofrowslessthenumberofbaseconstraints).Thisisthelengthofthett**cutsarray.ttcut_data**cuts;SPMamp;IN;SPMamp;DescriptionofthecutscorrespondingtotheaddedrowsofthecurrentLPformulation.Theuserissupposedtoknowaboutthecutscorrespondingtothebaseconstraints.ttintprevind;SPMamp;IN;SPMamp;Thelastvariableprocessed(_inline$-1$_inlineiftherewasnone)byscSYMPHONY.ttintnextind;SPMamp;IN;SPMamp;Thenextvariable(_inline$-1$_inlineiftherearenone)knowntoscSYMPHONY.;SPMamp;;SPMamp;ttint*real_nextind;SPMamp;OUT;SPMamp;Pointertotheuserindexofthenextvariable(_inline$-1$_inlineifthereisnone).ttdouble*colval;SPMamp;OUT;SPMamp;Valuesofthenonzeroentriesinthecolumnofthenextvariable.(Sufficientspaceisalreadyallocatedforthisarray.)ttint*colind;SPMamp;OUT;SPMamp;Rowindicesofthenonzeroentriesinthecolumn.(Sufficientspaceisalreadyallocatedforthisarray.)ttint*collen;SPMamp;OUT;SPMamp;Thelengthofthettcolvalandttcolindarrays.ttdouble*obj;SPMamp;OUT;SPMamp;Objectivecoefficientcorrespondingtothenextvariable.{tabular}/;
${$key} = ' <IMG WIDTH=645 HEIGHT=553 ALIGN=BOTTOM ALT="tabular1657" SRC="img69.gif"  > '; 
$key = q/{_inline}$leq${_inline}/;
${$key} = ' <IMG WIDTH=11 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline2624" SRC="img32.gif"  > '; 
$key = q/{tabular}llp265ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttint*extravarnum;SPMamp;OUT;SPMamp;Pointertothenumberofextraactivevariablesintheroot.ttint*extravars;SPMamp;OUT;SPMamp;Pointertoanarraycontainingalistofuserindicesoftheextravariablestobeactiveintheroot.{tabular}/;
${$key} = ' <IMG WIDTH=647 HEIGHT=99 ALIGN=BOTTOM ALT="tabular718" SRC="img18.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.scSYMPHONYignoreserrormessage.ttUSER_NO_PP;SPMamp;Userfreedeverythingintheuserspace.{tabular}/;
${$key} = ' <IMG WIDTH=444 HEIGHT=39 ALIGN=BOTTOM ALT="tabular1532" SRC="img37.gif"  > '; 
$key = q/{tabular}llp255ptttvoid*user;SPMamp;INOUT;SPMamp;Theuserdefinedpartofp.ttdoublelpetol;SPMamp;IN;SPMamp;The_inline$epsilon$_inlinetoleranceintheLPprocess.ttintvarnum;SPMamp;IN;SPMamp;Sameasthepreviousfunction.ttint*indices;SPMamp;IN;SPMamp;Sameasthepreviousfunction.ttdouble*values;SPMamp;IN;SPMamp;Sameasthepreviousfunction.ttcut_data*cut;SPMamp;IN;SPMamp;Pointertothecuttobetested.ttint*is_violated;SPMamp;OUT;SPMamp;TRUEFALSEbasedonwhetherthecutisviolatedornot.{tabular}/;
${$key} = ' <IMG WIDTH=645 HEIGHT=164 ALIGN=BOTTOM ALT="tabular1953" SRC="img94.gif"  > '; 
$key = q/{tabular}lp315ptttERROR;SPMamp;Error.Dothedefault.ttUSER_NO_PP;SPMamp;Userpackedthesolution.ttDEFAULT;SPMamp;Regulatedbytheparameterttpack_feasible_solution_default,butsettottSEND_NONZEROSunlessover-riddenbytheuser.ttSEND_NONZEROS;SPMamp;Packthenonzerovaluesandtheirindices.{tabular}/;
${$key} = ' <IMG WIDTH=636 HEIGHT=99 ALIGN=BOTTOM ALT="tabular1563" SRC="img47.gif"  > '; 
$key = q/{tabular}llp270ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintub;SPMamp;IN;SPMamp;Thecurrentbestupperbound.ttdoubleetol;SPMamp;IN;SPMamp;Epsilontolerance.ttbranch_obj*can;SPMamp;IN;SPMamp;Thebranchingcandidate.;SPMamp;;SPMamp;ttchar*action;SPMamp;OUT;SPMamp;Arrayofactionsforthechildren.Thearrayisalreadyallocatedtolengthttcan-;SPMgt;number.{tabular}/;
${$key} = ' <IMG WIDTH=641 HEIGHT=168 ALIGN=BOTTOM ALT="tabular1599" SRC="img55.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.Ignored.ttUSER_NO_PP;SPMamp;Theusersuccessfullyfreedthedatastructures.{tabular}/;
${$key} = ' <IMG WIDTH=464 HEIGHT=38 ALIGN=BOTTOM ALT="tabular2029" SRC="img100.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.Thiserrorisprobablynotfatal.ttUSER_NO_PP;SPMamp;Userexecutedfunctionsuccessfully.{tabular}/;
${$key} = ' <IMG WIDTH=401 HEIGHT=38 ALIGN=BOTTOM ALT="tabular705" SRC="img15.gif"  > '; 
$key = q/{tabular}llp280ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttintdg_id;SPMamp;IN;SPMamp;Theprocessidofthegraphdrawingprocess.{tabular}/;
${$key} = ' <IMG WIDTH=490 HEIGHT=38 ALIGN=BOTTOM ALT="tabular695" SRC="img12.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.scSYMPHONYstops.ttUSER_NO_PP;SPMamp;Allrequireddatafilledout,butnopost-processingdone.ttUSER_AND_PP;SPMamp;Allrequiredpost-processingdone.{tabular}/;
${$key} = ' <IMG WIDTH=548 HEIGHT=60 ALIGN=BOTTOM ALT="tabular720" SRC="img19.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.ttDEFAULTisused.ttUSER_NO_PP;SPMamp;Userfilledouttt*desc_sizeandtt*desc.ttDEFAULT;SPMamp;Nodescriptionisapped.{tabular}/;
${$key} = ' <IMG WIDTH=397 HEIGHT=59 ALIGN=BOTTOM ALT="tabular1618" SRC="img60.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Ignored.ttUSER_NO_PP;SPMamp;Messageisprocessed.{tabular}/;
${$key} = ' <IMG WIDTH=268 HEIGHT=38 ALIGN=BOTTOM ALT="tabular778" SRC="img30.gif"  > '; 
$key = q/{tabular}lp315ptttERROR;SPMamp;Error.Nomessagewillbesent.ttUSER_NO_PP;SPMamp;Userpackedandsentthemessage.ttDEFAULT;SPMamp;Regulatedbythettpack_lp_solution_defaultparameter,initiallysettottSEND_NOZEROS.ttSEND_NONZEROS;SPMamp;Suserindicesandvaluesofvariablesatnonzerolevel.ttSEND_FRACTIONS;SPMamp;Suserindicesandvaluesofvariablesatfractionallevel.{tabular}/;
${$key} = ' <IMG WIDTH=646 HEIGHT=121 ALIGN=BOTTOM ALT="tabular1640" SRC="img66.gif"  > '; 
$key = q/{tabular}llp290ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintwhich_sol;SPMamp;IN;SPMamp;Thetypeofsolutionpassedontothedisplayingfunction.PossiblevaluesarettDISP_FEAS_SOLUTION,ttDISP_RELAXED_SOLUTIONandttDISP_FINAL_RELAXED_SOLUTION.ttintvarnum;SPMamp;IN;SPMamp;Thenumberofvariablesinthecurrentsolutionatnonzerolevel(thelengthofthettindicesandttvaluesarrays).ttint*indices;SPMamp;IN;SPMamp;Userindicesofvariablesatnonzerolevelinthecurrentsolution.ttdouble*values;SPMamp;IN;SPMamp;Valuesofthenonzerovariables.{tabular}/;
${$key} = ' <IMG WIDTH=646 HEIGHT=229 ALIGN=BOTTOM ALT="tabular1568" SRC="img48.gif"  > '; 
$key = q/{tabular}lp310ptttERROR;SPMamp;Errorintheuserfunction.Printinganerrormessageistheuser'sresponsibility.Depingontheworktheuserfunctionwassupposedtodo,theerrormightbeignored(andsomedefaultoptionused),ortheprocessaborts.ttUSER_AND_PP;SPMamp;Theuserimplementedboththeuserfunctionandpost-processing(post-processingbyscSYMPHONYwillbeskipped).ttUSER_NO_PP;SPMamp;Theuserimplementedtheuserfunctiononly.ttDEFAULT;SPMamp;Thedefaultoptionisgoingtobeused(thedefaultisoneofthebuilt-inoptions,scSYMPHONYdecideswhichonetousebasedoninitialparametersettingsandtheexecutionofthealgorithm).ttbuilt_in_option1;SPMamp;ttbuilt_in_option2...;SPMamp;Thespecifiedbuilt-inoptionwillbeused.{tabular}/;
${$key} = ' <IMG WIDTH=683 HEIGHT=254 ALIGN=BOTTOM ALT="tabular206" SRC="img2.gif"  > '; 
$key = q/{tabular}llp250ptttvoid**user;SPMamp;INOUT;SPMamp;Pointertotheuser-defineddatastructure.{tabular}/;
${$key} = ' <IMG WIDTH=519 HEIGHT=13 ALIGN=BOTTOM ALT="tabular1783" SRC="img88.gif"  > '; 
$key = q/{tabular}lp330ptttERROR;SPMamp;Error.Interpretedasifnocutsweregenerated.ttUSER_NO_PP;SPMamp;CutsweregeneratedbutscSYMPHONYmustcomparethemtothoseinthelocalpool.ttUSER_AND_PP;SPMamp;CutsweregeneratedandscSYMPHONYshouldnotcomparethemtothoseinthelocalpool.ttDEFAULT;SPMamp;Nocutsaregenerated.(Atleastfornow.WemightaddGomorycutsfordefaultlater.){tabular}/;
${$key} = ' <IMG WIDTH=639 HEIGHT=146 ALIGN=BOTTOM ALT="tabular1671" SRC="img72.gif"  > '; 
$key = q/{tabular}llp280ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttintmsgtag;SPMamp;IN;SPMamp;Themessagetagofthemessage.{tabular}/;
${$key} = ' <IMG WIDTH=471 HEIGHT=38 ALIGN=BOTTOM ALT="tabular776" SRC="img29.gif"  > '; 
$key = q/{tabular}llp245ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttint*feas_sol_size;SPMamp;INOUT;SPMamp;Pointertosizeofthefeasiblesolutionpassedbytheuser.ttint**feas_sol;SPMamp;INOUT;SPMamp;Pointertothearrayofuserindicescontainingthefeasiblesolution.Thisarrayissimplycopiedbythetreemanagerandmustbefreedbytheuser.{tabular}/;
${$key} = ' <IMG WIDTH=645 HEIGHT=124 ALIGN=BOTTOM ALT="tabular768" SRC="img27.gif"  > '; 
$key = q/{_inline}$ttrhs+ttrange${_inline}/;
${$key} = ' <IMG WIDTH=93 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline2622" SRC="img31.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.scSYMPHONYstops.ttUSER_NO_PP;SPMamp;Initializationisdone.{tabular}/;
${$key} = ' <IMG WIDTH=320 HEIGHT=35 ALIGN=BOTTOM ALT="tabular665" SRC="img5.gif"  > '; 
$key = q/{_inline}$1^st${_inline}/;
${$key} = ' <IMG WIDTH=21 HEIGHT=12 ALIGN=BOTTOM ALT="tex2html_wrap_inline2648" SRC="img39.gif"  > '; 
$key = q/{tabular}lp210ptttERROR;SPMamp;Error.ttDEFAULTisused.ttUSER_NO_PP;SPMamp;Usergeneratedbranchingcandidates.ttDEFAULT;SPMamp;Regulatedbythettselect_candidates_defaultparameter(oneofthefollowingthreeoptions).ttUSER__CLOSE_TO_HALF;SPMamp;Choosevariableswithvaluesclosesttohalf.ttUSER__CLOSE_TO_HALF_AND_EXPENSIVE;SPMamp;Choosevariableswithvaluesclosetohalfandwithhighobjectivefunctioncoefficients.ttUSER__CLOSE_TO_ONE_AND_CHEAP;SPMamp;Choosevariableswithvaluesclosetooneandwithlowobjectivefunctioncoefficients.{tabular}/;
${$key} = ' <IMG WIDTH=641 HEIGHT=211 ALIGN=BOTTOM ALT="tabular1586" SRC="img52.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Ignored.ttUSER_NO_PP;SPMamp;Displayingisdone.{tabular}/;
${$key} = ' <IMG WIDTH=248 HEIGHT=38 ALIGN=BOTTOM ALT="tabular761" SRC="img26.gif"  > '; 
$key = q/{tabular}llp275ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttvoid**user_cp;SPMamp;OUT;SPMamp;Pointertotheuser-defineddatastructureforthecutpoolprocess.{tabular}/;
${$key} = ' <IMG WIDTH=640 HEIGHT=59 ALIGN=BOTTOM ALT="tabular753" SRC="img25.gif"  > '; 
$key = q/{tabular}llp280ptttvoid**user;SPMamp;INOUT;SPMamp;Pointertotheuser-defineddatastructure(shouldbettNULLonreturn).{tabular}/;
${$key} = ' <IMG WIDTH=642 HEIGHT=39 ALIGN=BOTTOM ALT="tabular671" SRC="img6.gif"  > '; 
$key = q/{tabular}lp340ptttERROR;SPMamp;Error.ttDEFAULTisused.ttUSER_NO_PP;SPMamp;Theuserfilledouttt*action(andpossiblytt*cand_numandtt*candidates).ttDEFAULT;SPMamp;actionissettothevalueoftheparameterttshall_we_branch_default,whichisinitiallyttUSER__BRANCH_IF_MUSTunlessover-riddenbytheuser.{tabular}/;
${$key} = ' <IMG WIDTH=646 HEIGHT=81 ALIGN=BOTTOM ALT="tabular1578" SRC="img51.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.ThisLPsolutionisnotprocessed.ttUSER_NO_PP;SPMamp;TheuserreceivedtheLPsolution.{tabular}/;
${$key} = ' <IMG WIDTH=418 HEIGHT=34 ALIGN=BOTTOM ALT="tabular1792" SRC="img81.gif"  > '; 
$key = q/{tabular}llp285ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintvarnum;SPMamp;IN;SPMamp;ThenumberofvariablescurrentlyintheLPrelaxation.(Thelengthofthett*varsandttxarrays.)ttvar_desc**vars;SPMamp;IN;SPMamp;ThevariablescurrentlyintheLPrelaxation.ttdouble*x;SPMamp;IN;SPMamp;Valuesoftheabovevariables.ttintwhere;SPMamp;IN;SPMamp;Wherethesolutionistobesent---ttLP_SOL_TO_CGorttLP_SOL_TO_CP.{tabular}/;
${$key} = ' <IMG WIDTH=645 HEIGHT=164 ALIGN=BOTTOM ALT="tabular1638" SRC="img65.gif"  > '; 
$key = q/{tabular}llp290ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttintmsgtag;SPMamp;IN;SPMamp;ttFEASIBLE_SOLUTION_NONZEROSorttFEASIBLE_SOLUTION_USERttdoublecost;SPMamp;IN;SPMamp;Thecostofthefeasiblesolution.ttintnumvars;SPMamp;IN;SPMamp;Thenumberofvariableswhoseuserindicesandvaluesweresent(lengthofttindicesandttvalues).ttint*indices;SPMamp;IN;SPMamp;Theuserindicesofthenonzerovariables.ttdouble*values;SPMamp;IN;SPMamp;Thecorrespondingvalues.{tabular}/;
${$key} = ' <IMG WIDTH=646 HEIGHT=146 ALIGN=BOTTOM ALT="tabular727" SRC="img20.gif"  > '; 
$key = q/{tabular}llp285ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttbranch_obj*can;SPMamp;IN;SPMamp;Thebranchingcandidate.ttcut_data*cut;SPMamp;IN;SPMamp;Thedescriptionofthecutifthebranchingobjectisacut.ttchar*action;SPMamp;IN;SPMamp;Arrayofactionsforthechildren.{tabular}/;
${$key} = ' <IMG WIDTH=636 HEIGHT=103 ALIGN=BOTTOM ALT="tabular1608" SRC="img57.gif"  > '; 
$key = q/{tabular}lp295.386ptttERROR;SPMamp;Error.ttDEFAULTisused.ttUSER_NO_PP;SPMamp;Userdidthecomparison,filledouttt*same_cuts.ttDEFAULT;SPMamp;Comparebytebybyte(seeabove).{tabular}/;
${$key} = ' <IMG WIDTH=469 HEIGHT=59 ALIGN=BOTTOM ALT="tabular1625" SRC="img62.gif"  > '; 
$key = q/{tabular}llp255ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintrownum;SPMamp;IN;SPMamp;Thenumberofwaitingrows.ttwaiting_row**rows;SPMamp;IN;SPMamp;Thearrayofwaitingrows.ttchar*delete;SPMamp;OUT;SPMamp;Anarrayofindicators(eachofthemisonettchar)showingwhichwaitingrowsaretobedeleted.{tabular}/;
${$key} = ' <IMG WIDTH=643 HEIGHT=124 ALIGN=BOTTOM ALT="tabular1688" SRC="img76.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.TheLPprocessisaborted.ttDEFAULT;SPMamp;Upperboundsaresettoone.ttUSER_NO_PP;SPMamp;Theuserfilleduptheupperboundarray.{tabular}/;
${$key} = ' <IMG WIDTH=421 HEIGHT=59 ALIGN=BOTTOM ALT="tabular1547" SRC="img43.gif"  > '; 
$key = q/{tabular}llp257ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintvarnum;SPMamp;IN;SPMamp;Numberofvariablesintherelaxation(baseandextra).ttvar_desc**vars;SPMamp;IN;SPMamp;Anarrayoflengthttncontainingtheuserindicesoftheactivevariables(baseandextra).ttintrownum;SPMamp;IN;SPMamp;Numberofconstraintsintherelaxation(baseandextra).ttintcutnum;SPMamp;IN;SPMamp;Numberofextraconstraints.ttcut_data**cuts;SPMamp;IN;SPMamp;Packeddescriptionofextraconstraints.;SPMamp;;SPMamp;ttint*nz;SPMamp;OUT;SPMamp;PointertothenumberofnonzerosintheLP.ttint**matbeg;SPMamp;INOUT;SPMamp;PointerstothearraysthatdescribetheLPproblem(seedescriptionabove.ttint**matind;SPMamp;INOUT;SPMamp;ttdouble**matval;SPMamp;INOUT;SPMamp;ttdouble**obj;SPMamp;INOUT;SPMamp;ttdouble**rhs;SPMamp;INOUT;SPMamp;ttchar**sense;SPMamp;INOUT;SPMamp;ttdouble**rngval;SPMamp;INOUT;SPMamp;;SPMamp;;SPMamp;ttint*maxn;SPMamp;INOUT;SPMamp;Themaximumnumberofvariables.ttint*maxm;SPMamp;INOUT;SPMamp;Themaximumnumberofconstraints.ttint*maxnz;SPMamp;INOUT;SPMamp;Themaximumnumberofnonzeros.;SPMamp;;SPMamp;ttint*allocn;SPMamp;INOUT;SPMamp;Thelengthofthett*matbegandtt*objarrays(shouldbett*maxm+*maxn+1).ttint*allocm;SPMamp;INOUT;SPMamp;Thelengthofthett*rhs,tt*senseandtt*rngvalarrays.ttint*allocnz;SPMamp;INOUT;SPMamp;Thelengthofthett*matvalandtt*matindarrays(shouldbett*maxnz+*maxm.{tabular}/;
${$key} = ' <IMG WIDTH=642 HEIGHT=618 ALIGN=BOTTOM ALT="tabular1538" SRC="img40.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Ignored.ttUSER_NO_PP;SPMamp;Theuserfunctionexitedproperly.{tabular}/;
${$key} = ' <IMG WIDTH=365 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1807" SRC="img85.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.Ignored.ttUSER_NO_PP;SPMamp;Theusersuccessfullyperformedinitialization.{tabular}/;
${$key} = ' <IMG WIDTH=455 HEIGHT=38 ALIGN=BOTTOM ALT="tabular2022" SRC="img99.gif"  > '; 
$key = q/{tabular}llp250ptttvoid**user;SPMamp;INOUT;SPMamp;Pointertotheuser-definedLPdatastructure.{tabular}/;
${$key} = ' <IMG WIDTH=548 HEIGHT=13 ALIGN=BOTTOM ALT="tabular1530" SRC="img36.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.scSYMPHONYstops.ttUSER_NO_PP;SPMamp;UserIOwascompletedsuccessfully.{tabular}/;
${$key} = ' <IMG WIDTH=387 HEIGHT=40 ALIGN=BOTTOM ALT="tabular689" SRC="img11.gif"  > '; 
$key = q/{tabular}llp225ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintvarnum;SPMamp;IN;SPMamp;ThenumberofvariablescurrentlyintheLPrelaxation.(Thelengthofthett*varsandttxarrays.)ttvar_desc**vars;SPMamp;IN;SPMamp;ThevariablescurrentlyintheLPrelaxation.ttdouble*x;SPMamp;IN;SPMamp;Valuesoftheabovevariables.ttint*new_row_num;SPMamp;OUT;SPMamp;Thenumberofcutsgenerated.ttwaiting_row***new_rows;SPMamp;OUT;SPMamp;Thecutsandthecorrespondingrows.{tabular}/;
${$key} = ' <IMG WIDTH=639 HEIGHT=189 ALIGN=BOTTOM ALT="tabular1669" SRC="img71.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;CutsarenotcheckedforthisLPsolution.ttUSER_NO_PP;SPMamp;Theuserispreparedtocheckcuts.{tabular}/;
${$key} = ' <IMG WIDTH=424 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1948" SRC="img93.gif"  > '; 
$key = q/{tabular}llp280ptttvoid**user;SPMamp;INOUT;SPMamp;Pointertotheuser-defineddatastructure.{tabular}/;
${$key} = ' <IMG WIDTH=519 HEIGHT=13 ALIGN=BOTTOM ALT="tabular1924" SRC="img88.gif"  > '; 
$key = q/{tabular}llp280ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttintiter_num;SPMamp;IN;SPMamp;TheiterationnumberofthecurrentLPsolution.ttintlevel;SPMamp;IN;SPMamp;ThelevelinthetreeonwhichthecurrentLPsolutionwasgenerated.ttindex;SPMamp;IN;SPMamp;TheindexofthenodeinwhichLPsolutionwasgenerated.ttobjval;SPMamp;IN;SPMamp;TheobjectivefunctionvalueofthecurrentLPsolution.ttintvarnum;SPMamp;IN;SPMamp;ThenumberofnonzerosinthecurrentLPsolution.ttindices;SPMamp;IN;SPMamp;ThecolumnindicesofthenonzerovariablesinthecurrentLPsolution.ttvalues;SPMamp;IN;SPMamp;Thevaluesofthenonzerovariableslistedinttindices.ttdoubleub;SPMamp;IN;SPMamp;Thecurrentglobalupperbound.ttdoublelpetol;SPMamp;IN;SPMamp;ThecurrenterrortoleranceintheLP.ttint*cutnum;SPMamp;OUT;SPMamp;PointertothenumberofcutsgeneratedandsenttotheLP.{tabular}/;
${$key} = ' <IMG WIDTH=641 HEIGHT=293 ALIGN=BOTTOM ALT="tabular1805" SRC="img84.gif"  > '; 
$key = q/{tabular}lp290ptttERROR;SPMamp;Error.ttDEFAULTisused.ttUSER_NO_PP;SPMamp;Userfilledouttt*which_is_better.ttDEFAULT;SPMamp;Regulatedbythettcompare_candidates_defaultparameter,initiallysettottLOWEST_LOW_OBJunlessover-riddenbytheuser.ttBIGGEST_DIFFERENCE;SPMamp;Preferthecandidatewiththebiggestdifferencebetweenhighestandlowestobjectivefunctionvalues.ttLOWEST_LOW;SPMamp;Preferthecandidatewiththelowestminimumobjectivefunctionvalue.Theminimumistakenovertheobjectivefunctionvaluesofallthechildren.ttHIGHEST_LOW;SPMamp;Preferthecandidatewiththehighestminimumobjectivefunctionvalue.ttLOWEST_HIGH;SPMamp;Preferthecandidatewiththelowestmaximumobjectivefunctionvalue.ttHIGHEST_HIGH;SPMamp;Preferthecandidatewiththehighestmaximumobjectivefunctionvalue.{tabular}/;
${$key} = ' <IMG WIDTH=643 HEIGHT=315 ALIGN=BOTTOM ALT="tabular1593" SRC="img54.gif"  > '; 
$key = q/{tabular}llp280ptttvoid**user;SPMamp;INOUT;SPMamp;Pointertotheuser-defineddatastructure(shouldbettNULLonexit).{tabular}/;
${$key} = ' <IMG WIDTH=642 HEIGHT=39 ALIGN=BOTTOM ALT="tabular1931" SRC="img90.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.IgnoredbyscSYMPHONY.ttUSER_NO_PP;SPMamp;Userchangedthestatiofthevariablesshewanted.{tabular}/;
${$key} = ' <IMG WIDTH=493 HEIGHT=39 ALIGN=BOTTOM ALT="tabular1648" SRC="img68.gif"  > '; 
$key = q/{tabular}llp250ptttvoid**user;SPMamp;OUT;SPMamp;Pointertotheuser-definedLPdatastructure.{tabular}/;
${$key} = ' <IMG WIDTH=528 HEIGHT=13 ALIGN=BOTTOM ALT="tabular1522" SRC="img34.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.TheLPprocessisaborted.ttUSER_NO_PP;SPMamp;Userfilledouttt*real_nextindandgenerateditscolumnifneeded.{tabular}/;
${$key} = ' <IMG WIDTH=584 HEIGHT=55 ALIGN=BOTTOM ALT="tabular1661" SRC="img70.gif"  > '; 
$key = q/{tabular}llp300ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttint*ub;SPMamp;OUT;SPMamp;Pointertotheglobalupperbound.Initially,theupperboundissettoeithertt-MAXDOUBLEortheboundreadinfromtheparameterfile,andshouldbechangedbytheuseronlyifabettervalidupperboundisfound.{tabular}/;
${$key} = ' <IMG WIDTH=646 HEIGHT=103 ALIGN=BOTTOM ALT="tabular703" SRC="img14.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.Thecutsarediscarded.ttUSER_NO_PP;SPMamp;Userunpackedthecuts.{tabular}/;
${$key} = ' <IMG WIDTH=337 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1632" SRC="img64.gif"  > '; 
$key = q/{tabular}llp265ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintrownum;SPMamp;IN;SPMamp;Thenumberofcutsadded.ttwaiting_row**rows;SPMamp;IN;SPMamp;Arrayofwaitingrowscontainingthecutsadded.{tabular}/;
${$key} = ' <IMG WIDTH=592 HEIGHT=81 ALIGN=BOTTOM ALT="tabular1681" SRC="img73.gif"  > '; 
$key = q/{tabular}lp330ptttERROR;SPMamp;Purgeeverysinglewaitingrow.ttUSER_AND_PP;SPMamp;Theuserremovedtheunwantedwaitingrowsandcompressedtheremaininglist.ttUSER_NO_PP;SPMamp;Theusermarkedinttdeletetherowstobedeleted.ttDEFAULT;SPMamp;Describedabove.{tabular}/;
${$key} = ' <IMG WIDTH=639 HEIGHT=99 ALIGN=BOTTOM ALT="tabular1690" SRC="img77.gif"  > '; 
$key = q/{tabular}lp317ptttERROR;SPMamp;Error.scSYMPHONYignoreserrormessage.ttUSER_NO_PP;SPMamp;Userdisplayedwhatevershewantedto.ttDEFAULT;SPMamp;Regulatedbytheparameterttdisplay_solution_default.ttDISP_NOTHING;SPMamp;Displaynothing.ttDISP_NZ_INT;SPMamp;Displayuserindices(asintegers)andvaluesofnonzerovariables.ttDISP_NZ_HEXA;SPMamp;Displayuserindices(ashexadecimals)andvaluesofnonzerovariables.ttDISP_FRAC_INT;SPMamp;Displayuserindices(asintegers)andvaluesofvariablesnotattheirlowerorupperbounds.ttDISP_FRAC_HEXA;SPMamp;Displayuserindices(ashexadecimals)andvaluesofvariablesnotattheirlowerandupperbounds.{tabular}/;
${$key} = ' <IMG WIDTH=645 HEIGHT=233 ALIGN=BOTTOM ALT="tabular1570" SRC="img49.gif"  > '; 
$key = q/{tabular}llp275ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttvoid**user_cg;SPMamp;OUT;SPMamp;Pointertotheuser-defineddatastructureforthecutgeneratorprocess.{tabular}/;
${$key} = ' <IMG WIDTH=639 HEIGHT=59 ALIGN=BOTTOM ALT="tabular744" SRC="img24.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Ignored.Thisisprobablynotafatalerror.ttUSER_NO_PP;SPMamp;Everythingwasfreedsuccessfully.{tabular}/;
${$key} = ' <IMG WIDTH=432 HEIGHT=38 ALIGN=BOTTOM ALT="tabular673" SRC="img7.gif"  > '; 
$key = q/{_inline}$^ttth${_inline}/;
${$key} = ' <IMG WIDTH=14 HEIGHT=8 ALIGN=BOTTOM ALT="tex2html_wrap_inline2670" SRC="img75.gif"  > '; 
$key = q/{tabular}llp250ptttvoid*user;SPMamp;INOUT;SPMamp;Pointertotheuser-defineddatastructure.ttinttext_length;SPMamp;IN;SPMamp;Thelengthoftttext.ttchar*text;SPMamp;IN;SPMamp;ttintowner_tid;SPMamp;IN;SPMamp;Thetidoftheprocessthatinitiatedthiswindow.{tabular}/;
${$key} = ' <IMG WIDTH=608 HEIGHT=81 ALIGN=BOTTOM ALT="tabular2034" SRC="img101.gif"  > '; 
$key = q/cached_env_img/;
${$key} = ''; 
$key = q/{tabular}llp275ptttvoid**user;SPMamp;INOUT;SPMamp;Pointertotheuser-defineddatastructure.ttwindow*win;SPMamp;INOUT;SPMamp;{tabular}/;
${$key} = ' <IMG WIDTH=519 HEIGHT=35 ALIGN=BOTTOM ALT="tabular2020" SRC="img98.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Ignored.Thisisprobablynotafatalerror.ttUSER_NO_PP;SPMamp;Thesolutionhasbeenunpackedandstored.{tabular}/;
${$key} = ' <IMG WIDTH=440 HEIGHT=38 ALIGN=BOTTOM ALT="tabular729" SRC="img21.gif"  > '; 
$key = q/{_inline}$0^th${_inline}/;
${$key} = ' <IMG WIDTH=23 HEIGHT=15 ALIGN=BOTTOM ALT="tex2html_wrap_inline2646" SRC="img38.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.scSYMPHONYstops.ttUSER_NO_PP;SPMamp;Packingisdone.{tabular}/;
${$key} = ' <IMG WIDTH=320 HEIGHT=39 ALIGN=BOTTOM ALT="tabular737" SRC="img23.gif"  > '; 
$key = q/{tabular}llp280ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttchar*filename;SPMamp;IN;SPMamp;Thenameoftheparameterfile.{tabular}/;
${$key} = ' <IMG WIDTH=507 HEIGHT=38 ALIGN=BOTTOM ALT="tabular679" SRC="img8.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.CGexits.ttUSER_NO_PP;SPMamp;Theuserreceivedthedataproperly.{tabular}/;
${$key} = ' <IMG WIDTH=381 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1785" SRC="img79.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.IgnoredbyscSYMPHONY.ttUSER_NO_PP;SPMamp;Theuserprintedoutwhatevershewantedto.{tabular}/;
${$key} = ' <IMG WIDTH=453 HEIGHT=39 ALIGN=BOTTOM ALT="tabular1610" SRC="img58.gif"  > '; 
$key = q/{tabular}llp275ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttcut_data*cut1;SPMamp;IN;SPMamp;Thefirstcut.ttcut_data*cut2;SPMamp;IN;SPMamp;Thesecondcut.ttint*same_cuts;SPMamp;OUT;SPMamp;Possiblevalues:ttSAME,ttFIRST_CUT_BETTER,ttSECOND_CUT_BETTERandttDIFFERENT(i.e.,notcomparable).{tabular}/;
${$key} = ' <IMG WIDTH=640 HEIGHT=146 ALIGN=BOTTOM ALT="tabular1623" SRC="img61.gif"  > '; 
$key = q/{tabular}llp265ptttvoid*user;SPMamp;INOUT;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttdoublelpetol;SPMamp;IN;SPMamp;The_inline$epsilon$_inlinetoleranceoftheLPsolver.ttintvarnum;SPMamp;IN;SPMamp;Thelengthofthettindicesandttvaluesarrays.ttint*indices;SPMamp;IN;SPMamp;Userindicesofvariablesatnonzerolevelinthecurrentsolution.ttdouble*values;SPMamp;IN;SPMamp;Valuesofthevariableslistedinttindices.;SPMamp;;SPMamp;ttint*feasible;SPMamp;OUT;SPMamp;Feasibilitystatusofthesolution(ttNOT_FEASIBLE,orttFEASIBLE).{tabular}/;
${$key} = ' <IMG WIDTH=646 HEIGHT=211 ALIGN=BOTTOM ALT="tabular1554" SRC="img44.gif"  > '; 
$key = q/{tabular}lp330ptttERROR;SPMamp;Error.TheLPprocessisaborted.ttUSER_AND_PP;SPMamp;Post-processingwillbeskipped,theuseraddedtheconstraintscorrespondingtothecuts.ttUSER_NO_PP;SPMamp;Usercreatedthematrixwithonlythebaseconstraints.{tabular}/;
${$key} = ' <IMG WIDTH=638 HEIGHT=81 ALIGN=BOTTOM ALT="tabular1540" SRC="img41.gif"  > '; 
$key = q/{tabular}llp250ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.{tabular}/;
${$key} = ' <IMG WIDTH=471 HEIGHT=12 ALIGN=BOTTOM ALT="tabular1790" SRC="img80.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Ignored.ttUSER_NO_PP;SPMamp;Theuserisdonecheckingthecut.{tabular}/;
${$key} = ' <IMG WIDTH=365 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1814" SRC="img87.gif"  > '; 
$key = q/{tabular}llp285ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttintvarnum;SPMamp;IN;SPMamp;Thenumberofnonzerofractionalvariablesdescribedinttindicesandttvalues.ttint*indices;SPMamp;IN;SPMamp;Theuserindicesofthenonzerofractionalvariables.ttdouble*values;SPMamp;IN;SPMamp;Thenonzerofractionalvalues.{tabular}/;
${$key} = ' <IMG WIDTH=639 HEIGHT=104 ALIGN=BOTTOM ALT="tabular1946" SRC="img92.gif"  > '; 
$key = q/{tabular}llp250ptttvoid*user;SPMamp;INOUT;SPMamp;Pointertotheuser-defineddatastructure.ttwindow*win;SPMamp;INOUT;SPMamp;Thewindowthatreceivedthemessage.ttFILE*write_to;SPMamp;IN;SPMamp;Pipetothewishprocess.{tabular}/;
${$key} = ' <IMG WIDTH=544 HEIGHT=59 ALIGN=BOTTOM ALT="tabular2013" SRC="img96.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.scSYMPHONYstops.ttUSER_NO_PP;SPMamp;Theusercompletedinitializationsuccessfully.{tabular}/;
${$key} = ' <IMG WIDTH=453 HEIGHT=39 ALIGN=BOTTOM ALT="tabular697" SRC="img13.gif"  > '; 
$key = q/{tabular}lp265ptttERROR;SPMamp;Error.ttDEFAULTisused.ttUSER_NO_PP;SPMamp;Userfilledouttt*action.ttUSER_AND_PP;SPMamp;Userfilledouttt*actionanddidanequivalentofthepost-processing.ttDEFAULT;SPMamp;Regulatedbythettselect_child_defaultparameter,whichisinitiallysettottPREFER_LOWER_OBJ_VALUE,unlessover-riddenbytheuser.ttPREFER_HIGHER_OBJ_VALUE;SPMamp;Choosechildwiththehighestobjectivevalue.ttPREFER_LOWER_OBJ_VALUE;SPMamp;Choosechildwiththelowestobjectivevalue.{tabular}/;
${$key} = ' <IMG WIDTH=642 HEIGHT=189 ALIGN=BOTTOM ALT="tabular1601" SRC="img56.gif"  > '; 
$key = q/{tabular}llp260ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintvarnum;SPMamp;IN;SPMamp;ThenumberofvariablescurrentlyintheLPrelaxation.(Thelengthofthett*varsandttxarrays.)ttvar_desc**vars;SPMamp;IN;SPMamp;ThevariablescurrentlyintheLPrelaxation.ttdouble*x;SPMamp;IN;SPMamp;Valuesoftheabovevariables.ttchar*status;SPMamp;INOUT;SPMamp;StatiofvariablescurrentlyintheLPrelaxation.{tabular}/;
${$key} = ' <IMG WIDTH=644 HEIGHT=146 ALIGN=BOTTOM ALT="tabular1646" SRC="img67.gif"  > '; 
$key = q/{tabular}llp250ptttvoid**user;SPMamp;OUT;SPMamp;Pointertotheuser-defineddatastructure.{tabular}/;
${$key} = ' <IMG WIDTH=500 HEIGHT=13 ALIGN=BOTTOM ALT="tabular663" SRC="img4.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;CutisnotsenttotheLP,regardlessofthevalueoftt*is_violated.ttUSER_NO_PP;SPMamp;Theuserfunctionexitedproperly.{tabular}/;
${$key} = ' <IMG WIDTH=584 HEIGHT=59 ALIGN=BOTTOM ALT="tabular1955" SRC="img95.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.Solutionisconsideredtobenotfeasible.ttUSER_NO_PP;SPMamp;UsercheckedIPfeasibility.ttDEFAULT;SPMamp;Regulatedbytheparameterttis_feasible_default,butsettottTEST_INTEGRALITYunlessover-riddenbytheuser.ttTEST_INTEGRALITY;SPMamp;Testintegralityofthegivensolution.ttTEST_ZERO_ONE;SPMamp;Testswhetherthesolutionisbinary.{tabular}/;
${$key} = ' <IMG WIDTH=639 HEIGHT=124 ALIGN=BOTTOM ALT="tabular1556" SRC="img45.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Ignored.ttUSER_NO_PP;SPMamp;Theuserfreedalldatastructures.{tabular}/;
${$key} = ' <IMG WIDTH=365 HEIGHT=34 ALIGN=BOTTOM ALT="tabular1800" SRC="img83.gif"  > '; 
$key = q/{tabular}llp225ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttintfrom;SPMamp;IN;SPMamp;Seebelowin``Notes''.ttintone_row_only;SPMamp;IN;SPMamp;ttUNPACK_CUTS_SINGLEorttUNPACK_CUTS_MULTIPLE(seenotesbelow).ttintvarnum;SPMamp;IN;SPMamp;Thenumberofvariables.ttvar_desc**vars;SPMamp;IN;SPMamp;Thevariablescurrentlyintheproblem.ttintcutnum;SPMamp;IN;SPMamp;Thenumberofcutstobedecoded.ttcut_data**cuts;SPMamp;IN;SPMamp;CutsthatneedtobeconvertedtorowsforthecurrentLP.See``Warning''below.;SPMamp;;SPMamp;ttint*new_row_num;SPMamp;OUT;SPMamp;Pointertothenumberofrowsintt**new_rows.ttwaiting_row***new_rows;SPMamp;OUT;SPMamp;Pointertothearrayofpointerstothenewrows.{tabular}/;
${$key} = ' <IMG WIDTH=640 HEIGHT=276 ALIGN=BOTTOM ALT="tabular1630" SRC="img63.gif"  > '; 
$key = q/{tabular}llp280ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttcut_data*new_cut;SPMamp;IN;SPMamp;Pointertothecutthatmustbechecked.{tabular}/;
${$key} = ' <IMG WIDTH=530 HEIGHT=34 ALIGN=BOTTOM ALT="tabular1812" SRC="img86.gif"  > '; 
$key = q/{tabular}llp290ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-definedLPdatastructure.;SPMamp;;SPMamp;ttdoublelpetol;SPMamp;IN;SPMamp;The_inline$epsilon$_inlinetoleranceoftheLPsolver.ttintvarnum;SPMamp;IN;SPMamp;Thelengthofthettindicesandttvaluesarrays.ttint*indices;SPMamp;IN;SPMamp;Userindicesofvariablesatnonzerolevelinthecurrentsolution.ttdouble*values;SPMamp;IN;SPMamp;Valuesofthevariableslistedinttindices.{tabular}/;
${$key} = ' <IMG WIDTH=646 HEIGHT=143 ALIGN=BOTTOM ALT="tabular1561" SRC="img46.gif"  > '; 
$key = q/{tabular}llp280ptttvoid**user;SPMamp;INOUT;SPMamp;Pointertotheuser-defineddatastructure(shouldbettNULLonexitfromthisfunction).{tabular}/;
${$key} = ' <IMG WIDTH=642 HEIGHT=39 ALIGN=BOTTOM ALT="tabular1798" SRC="img82.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;Error.scSYMPHONYstops.ttUSER_NO_PP;SPMamp;Therequireddataarefilledin,butnopost-processingdone.ttUSER_AND_PP;SPMamp;Allrequiredpost-processingdone.{tabular}/;
${$key} = ' <IMG WIDTH=573 HEIGHT=60 ALIGN=BOTTOM ALT="tabular712" SRC="img17.gif"  > '; 
$key = q/{tabular}llp245ptttvoid*user;SPMamp;IN;SPMamp;Pointertotheuser-defineddatastructure.ttint*varnum;SPMamp;OUT;SPMamp;Pointertothenumberofbasevariables.ttint**userind;SPMamp;OUT;SPMamp;Pointertoanarraycontainingtheuserindicesofthebasevariables.ttint**lb;SPMamp;OUT;SPMamp;Pointertoanarraycontainingthelowerboundsforthebasevariables.ttint**ub;SPMamp;OUT;SPMamp;Pointertoanarraycontainingtheupperboundsforthebasevariables.ttint*cutnum;SPMamp;OUT;SPMamp;Thenumberofbaseconstraints.ttint*colgen_strat;SPMamp;INOUT;SPMamp;Thedefaultstrategyoronethathasbeenreadinfromtheparameterfileispassedin,buttheuserisfreetochangeit.Seettcolgen_stratinthedescriptionofparametersfordetailsonhowtosetit.{tabular}/;
${$key} = ' <IMG WIDTH=641 HEIGHT=276 ALIGN=BOTTOM ALT="tabular710" SRC="img16.gif"  > '; 
$key = q/{tabular}lp300ptttERROR;SPMamp;CutsarenotcheckedforthisLPsolution.ttUSER_NO_PP;SPMamp;Theuserfunctionexitedproperly.{tabular}/;
${$key} = ' <IMG WIDTH=424 HEIGHT=38 ALIGN=BOTTOM ALT="tabular1940" SRC="img91.gif"  > '; 

1;

