#! /bin/tcsh -f

foreach dir (Template Vrp MATCH MPP SPP SPP+CUTS)
cd $1/SYMPHONY/$dir
foreach solver (CPLEX OSL)
echo ================= Compiling $dir with $solver ===============
make LP_SOLVER=$solver
end
foreach solver (CPLEX OSL CLP GLPK)
echo ================= Compiling $dir with OSI_$solver ===============
make LP_SOLVER=OSI OSI_INTERFACE=$solver
end
end

