/* include/config_sym.h.  Generated by configure.  */
/* include/config_sym.h.in.  Generated from configure.ac by autoheader.  */

/* If defined, debug sanity checks are performed during runtime */
/* #undef COIN_DEBUG */

/* Define to 1 if the Cgl package is used */
#define COIN_HAS_CGL 1

/* Define to 1 if the Clp package is used */
#define COIN_HAS_CLP 1

/* Define to 1 if the CoinUtils package is used */
#define COIN_HAS_COINUTILS 1

/* Define to 1 if the Cplex package is used */
/* #undef COIN_HAS_CPX */

/* Define to 1 if the Glpk package is used */
/* #undef COIN_HAS_GLPK */

/* Define to 1 if the Osi package is used */
#define COIN_HAS_OSI 1

/* Define to 1 if the Osl package is used */
/* #undef COIN_HAS_OSL */

/* Define to 1 if readline is available */
/* #undef COIN_HAS_READLINE */

/* Define to 1 if the Soplex package is used */
/* #undef COIN_HAS_SPX */

/* Define to 1 if the Xpress package is used */
/* #undef COIN_HAS_XPR */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <readline/readline.h> header file. */
/* #undef HAVE_READLINE_READLINE_H */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "symphony"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "coin-symphony@list.coin-or.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "SYMPHONY"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "SYMPHONY 5.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "symphony"

/* Define to the version of this package. */
#define PACKAGE_VERSION "5.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Default solver is chosen... */
#define SYM_DEFAULT_SOLVER "clp"

/* Version number of package */
#define VERSION "5.1"
