#!/bin/tcsh -f

foreach file (eil13 eil22 eil23 eil30 eil31 eil33 bayg29 bays29 ulysses16 ulysses22 gr17 gr21 gr24 fri26 swiss42 gr48 hk48 att48 eil51 A/A-n32-k5 A/A-n33-k5 A/A-n33-k6 A/A-n34-k5 A/A-n36-k5 A/A-n37-k5 A/A-n38-k5 A/A-n39-k5 A/A-n39-k6 A/A-n45-k6 A/A-n46-k7 B/B-n31-k5 B/B-n34-k5 B/B-n35-k5 B/B-n38-k6 B/B-n39-k5 B/B-n41-k6 B/B-n43-k6 B/B-n44-k7 B/B-n45-k5 B/B-n50-k7 B/B-n51-k7 B/B-n52-k7 B/B-n56-k7 B/B-n64-k9 A/A-n48-k7 A/A-n53-k7)

echo ====================== $file:r ======================= 
echo
$1/SYMPHONY/Vrp/bin.LINUX/CPLEX/vrp -F $1/vrplib/$file.vrp -S $1/small_graph/$file.sg 
$1/SYMPHONY/Vrp/bin.LINUX/OSL/vrp -F $1/vrplib/$file.vrp -S $1/small_graph/$file.sg 
$1/SYMPHONY/Vrp/bin.LINUX/OSI_CPLEX/vrp -F $1/vrplib/$file.vrp -S $1/small_graph/$file.sg 
$1/SYMPHONY/Vrp/bin.LINUX/OSI_OSL/vrp -F $1/vrplib/$file.vrp -S $1/small_graph/$file.sg 
$1/SYMPHONY/Vrp/bin.LINUX/OSI_CLP/vrp -F $1/vrplib/$file.vrp -S $1/small_graph/$file.sg 
$1/SYMPHONY/Vrp/bin.LINUX/OSI_GLPK/vrp -F $1/vrplib/$file.vrp -S $1/small_graph/$file.sg 
echo

end

